GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6336497164f440f10e8bb4b2


###

POST http://localhost:3000/subscribers
Content-type: application/json

{
  "name": "Amazing Person",
  "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE  http://localhost:3000/subscribers/6336497164f440f10e8bb4b2

###

PATCH  http://localhost:3000/subscribers/6336497164f440f10e8bb4b2
Content-Type: application/json

{
  "name": "New Amazing Person"
}